name: coreprotectbrush
version: '${version}'

main: org.funiki.coreprotectbrush.Coreprotectbrush
api-version: '26.1.2'
load: POSTWORLD
dependencies:
  server:
    CoreProtect:
      load: BEFORE
      required: true
      join-classpath: true